---
- hosts: webservers
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      state: present
    when: ansible_os_family =="Debian"

  - name: install wget
    apt:
      namee: wget
      state: present
    when: ansible_os_family =="Debian"
    
  - name: install tree
    apt:
      name: tree
      state: present
    when: ansible_os_family =="Debian"
    