---
- hosts: webservers
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webservers on ubuntu16
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"

  - name: start the webservers
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"
    