---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver on Ubuntu16
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"

  - name: start webserver on Ubuntu16
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"

  - name : install  webserver on Redhat8
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"
  - name: start webserver on Redhat8
    service:
      name: httpd
      state: started
    when: ansible_os_family =="RedHat"


